<?php
/**
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>

<?php if($filter instanceof Magento\CatalogSearch\Model\Layer\Filter\Price ):?>
<?php $range =  $this->getPriceRange($filter);?>
<?php $url = $this->getFilterUrl($filter);?>
<?php //var_dump($url);?>
<script>
var price_url = "<?=$url;?>";
require([
    'jquery',
    "jquery/ui",
    'domReady!'
], function($){
    $("div#price-slider").slider({
			range: true,
			min: <?=$range['min']?>,
			max: <?=$range['max']?>,
			values: [ <?=$range['min']?>, <?=$range['max']?> ],
			slide: function( event, ui ) {
				$( "#amount-min" ).val(ui.values[ 0 ]+ "$");
                $( "#amount-max" ).val(ui.values[ 1 ]+ "$");
			},
			change: function( event, ui ) {
				//alert(ui.values[0]+"~"+ui.values[1]);
				window.location.href = price_url+ui.values[0]+"-"+ui.values[1];
			}
		});
        $( "#amount-min" ).val( " " + $( "#price-slider" ).slider( "values", 0 ) +
        " $ ");
        $( "#amount-max" ).val( " " + $( "#price-slider" ).slider( "values", 1 ) +
        " $ ");
});
</script>
<?php 
?>      
<p style="display: flex;">
	<input type="text" id="amount-min" readonly style="border:0; color:#f6931f; font-weight:bold; width: 50%; text-align: left;">
    <input type="text" id="amount-max" readonly style="border:0; color:#f6931f; font-weight:bold; width: 50%; text-align: right;">
</p>
<div id="price-slider"></div>

<?php else:?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="my item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
<?php endif;?>
